<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>EMQX 服务器建立SSL/TLS安全连接、单向、双向 - 编程小白</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程小白" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程小白</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">EMQX 服务器建立SSL/TLS安全连接、单向、双向</h1>
			
		</header>
		<div class="content post__content clearfix">
			


        
                <div id="content_views" class="htmledit_views">
                    <p id="main-toc"><strong>目录</strong></p> 
<p id="SSL%2FTLS%E7%AE%80%E4%BB%8B-toc" style="margin-left:40px"><a href="#SSL%2FTLS%E7%AE%80%E4%BB%8B">SSL/TLS简介</a></p> 
<p id="TLS%E5%8D%8F%E8%AE%AE%E7%9A%84%E6%9E%B6%E6%9E%84-toc" style="margin-left:40px"><a href="#TLS%E5%8D%8F%E8%AE%AE%E7%9A%84%E6%9E%B6%E6%9E%84">TLS协议的架构</a></p> 
<p id="TLS%E8%AE%B0%E5%BD%95%E5%8D%8F%E8%AE%AE%C2%A0-toc" style="margin-left:40px"><a href="#TLS%E8%AE%B0%E5%BD%95%E5%8D%8F%E8%AE%AE%C2%A0">TLS记录协议 </a></p> 
<p id="%E6%8F%A1%E6%89%8B%E5%8D%8F%E8%AE%AE-toc" style="margin-left:40px"><a href="#%E6%8F%A1%E6%89%8B%E5%8D%8F%E8%AE%AE">握手协议</a></p> 
<p id="%E4%BB%80%E4%B9%88%E6%98%AF%E4%B8%BB%E5%AF%86%E7%A0%81%EF%BC%9F-toc" style="margin-left:80px"><a href="#%E4%BB%80%E4%B9%88%E6%98%AF%E4%B8%BB%E5%AF%86%E7%A0%81%EF%BC%9F">什么是主密码？</a></p> 
<p id="%E4%BB%80%E4%B9%88%E6%98%AF%E9%A2%84%E5%A4%87%E4%B8%BB%E5%AF%86%E7%A0%81%EF%BC%9F%C2%A0-toc" style="margin-left:80px"><a href="#%E4%BB%80%E4%B9%88%E6%98%AF%E9%A2%84%E5%A4%87%E4%B8%BB%E5%AF%86%E7%A0%81%EF%BC%9F%C2%A0">什么是预备主密码？ </a></p> 
<p id="SSL%2FTLS%E4%BC%98%E5%8A%BF-toc" style="margin-left:40px"><a href="#SSL%2FTLS%E4%BC%98%E5%8A%BF">SSL/TLS优势</a></p> 
<p id="SSL%2FTLS%E5%8D%8F%E8%AE%AE-toc" style="margin-left:40px"><a href="#SSL%2FTLS%E5%8D%8F%E8%AE%AE">SSL/TLS协议</a></p> 
<p id="%C2%A0SSL%2FTLS%20%E5%8D%95%E5%90%91%E9%AA%8C%E8%AF%81-toc" style="margin-left:40px"><a href="#%C2%A0SSL%2FTLS%20%E5%8D%95%E5%90%91%E9%AA%8C%E8%AF%81"> SSL/TLS 单向验证</a></p> 
<p id="MQTT%20%E8%BF%9E%E6%8E%A5%E6%B5%8B%E8%AF%95%EF%BC%88OpenSSL%EF%BC%89-toc" style="margin-left:80px"><a href="#MQTT%20%E8%BF%9E%E6%8E%A5%E6%B5%8B%E8%AF%95%EF%BC%88OpenSSL%EF%BC%89">MQTT 连接测试（OpenSSL）</a></p> 
<p id="emqx-dashboard-验证-toc" style="margin-left:80px"><a href="#emqx-dashboard-%E9%AA%8C%E8%AF%81">EMQX Dashboard 验证</a></p> 
<p id="SSL%2FTLS%20%E5%8F%8C%E5%90%91%E9%AA%8C%E8%AF%81-toc" style="margin-left:40px"><a href="#SSL%2FTLS%20%E5%8F%8C%E5%90%91%E9%AA%8C%E8%AF%81">SSL/TLS 双向验证</a></p> 
<hr> 
<h2 id="SSL%2FTLS%E7%AE%80%E4%BB%8B">SSL/TLS简介</h2> 
<blockquote> 
 <p>SSL/TLS是一种<strong>密码通信框架</strong>，他是世界上使用最广泛的密码通信方法。SSL/TLS综合运用了密码学中的对称密码，消息认证码，公钥密码，数字签名，伪随机数生成器等，可以说是密码学中的集大成者。</p> 
 <p> </p> 
</blockquote> 
<h2 id="%E2%80%8B%E7%BC%96%E8%BE%91%C2%A0">
<img alt="" height="303" src="https://images2.imgbox.com/60/ef/8dMcojUQ_o.png" width="868"> </h2> 
<h2 id="TLS%E5%8D%8F%E8%AE%AE%E7%9A%84%E6%9E%B6%E6%9E%84">TLS协议的架构</h2> 
<p><img alt="" height="161" src="https://images2.imgbox.com/19/76/cTGtaWYX_o.png" width="754"></p> 
<blockquote> 
 <p>TLS主要分为两层，底层的是TLS记录协议，主要负责使用对称密码对消息进行加密。</p> 
 <p>上层的是TLS握手协议，主要分为握手协议，密码规格变更协议和应用数据协议4个部分。</p> 
 <ul>
<li>握手协议负责在客户端和服务器端商定密码算法和共享密钥，包括证书认证，是4个协议中最最复杂的部分。</li>
<li>密码规格变更协议负责向通信对象传达变更密码方式的信号</li>
<li>警告协议负责在发生错误的时候将错误传达给对方</li>
<li>应用数据协议负责将TLS承载的应用数据传达给通信对象的协议。</li>
</ul> 
</blockquote> 
<h2 id="TLS%E8%AE%B0%E5%BD%95%E5%8D%8F%E8%AE%AE%C2%A0">TLS记录协议 </h2> 
<p>消息首先将会被分段，然后压缩，再计算其消息验证码，然后使用对称密码进行加密，加密使用的是CBC模式，CBC模式的初始向量是通过主密码来生成的。</p> 
<p>得到密文之后会附加类型，版本和长度等其他信息，最终组成最后的报文数据。</p> 
<p></p> 
<h2 id="%E6%8F%A1%E6%89%8B%E5%8D%8F%E8%AE%AE">握手协议</h2> 
<p><img alt="" height="721" src="https://images2.imgbox.com/a4/1a/VA86anUl_o.png" width="895"></p> 
<blockquote> 
 <p> 注：</p> 
 <p>1、这里可用版本号，可用的密码套件清单，可用的压缩方式清单就是向服务器询问对方支持哪些服务。</p> 
 <p>2、客户端随机数和服务器随机数是用来生成对称密钥的随机数。</p> 
 <p>3、可选步骤:certificate服务器端发送自己的证书清单，因为证书可能是层级结构的，所以处理服务器自己的证书之外，还需要发送为服务器签名的证书。客户端将会对服务器端的证书进行验证。如果是以匿名的方式通信则不需要证书。</p> 
 <p>4、可选步骤:ServerKeyExchange，如果第三步的证书信息不足，则可以发送ServerKeyExchange用来构建加密通道。</p> 
 <p>ServerKeyExchange的内容可能包含两种形式：</p> 
 <ul>
<li>如果选择的是RSA协议，那么传递的就是RSA构建公钥密码的参数（E，N）。我们回想一下RSA中构建公钥的公式：密文=明文^E mod N密文=明文<em>E</em><em>mod</em><em>N</em>， 只要知道了E和N，那么就知道了RSA的公钥，这里传递的就是E，N两个数字。</li>
<li>如果选择的是Diff-Hellman密钥交换协议，那么传递的就是密钥交换的参数。</li>
</ul> 
 <p>5、可选步骤:CertificateRequest如果是在一个受限访问的环境，比如fabric中，服务器端也需要向客户端索要证书。如果并不需要客户端认证，则不需要此步骤。</p> 
 <p>6、server hello done，服务器端发送server hello done的消息告诉客户端自己的消息结束了。</p> 
 <p>7、可选步骤:Certificate，客户端发送客户端证书给服务器</p> 
 <p>8、</p> 
 <p>ClientKeyExchange分两种情况：</p> 
 <ul>
<li>如果是公钥或者RSA模式情况下，客户端将根据客户端生成的随机数和服务器端生成的随机数，生成预备主密码，通过该公钥进行加密，返送给服务器端。</li>
<li>如果使用的是Diff-Hellman密钥交换协议，则客户端会发送自己这一方要生成Diff-Hellman密钥而需要公开的值。具体内容可以参考<a href="https://link.zhihu.com/?target=http%3A//www.flydean.com/diffie-hellman/" title="更加安全的密钥生成方法Diffie-Hellman">更加安全的密钥生成方法Diffie-Hellman</a>，这样服务器端可以根据这个公开值计算出预备主密码。</li>
</ul> 
 <p>9、可选步骤:CertificateVerify客户端向服务器端证明自己是客户端证书的持有者。</p> 
 <p>10、ChangeCipherSpec(准备切换密码)，ChangeCipherSpec是密码规格变更协议的消息，表示后面的消息将会以前面协商过的密钥进行加密。</p> 
 <p>11、finished(握手协议结束)，客户端告诉服务器端握手协议结束了。</p> 
 <p>12、ChangeCipherSpec(准备切换密码)，服务器端告诉客户端自己要切换密码了。</p> 
 <p>13、finished(握手协议结束)，服务器端告诉客户端，握手协议结束了。</p> 
 <p>14、切换到应用数据协议，这之后服务器和客户端就是以加密的方式进行沟通了。</p> 
</blockquote> 
<h3 id="%E4%BB%80%E4%B9%88%E6%98%AF%E4%B8%BB%E5%AF%86%E7%A0%81%EF%BC%9F">什么是主密码？</h3> 
<ul>
<li>主密码是根据密码套件中定义的单向散列函数实现的<strong><span style="color:#ed7976">伪随机数生成器+预备主密码+客户端随机数+服务器端随机数</span></strong>生成的。</li>
<li>主密码主要用来生成对称密码的密钥，消息认证码的密钥和对称密码的CBC模式所使用的初始化向量。</li>
</ul> 
<h3 id="%E4%BB%80%E4%B9%88%E6%98%AF%E9%A2%84%E5%A4%87%E4%B8%BB%E5%AF%86%E7%A0%81%EF%BC%9F%C2%A0">什么是预备主密码？ </h3> 
<ul>
<li>如果是公钥或者RSA模式情况下，客户端将根据客户端生成的随机数和服务器端生成的随机数，生成预备主密码，通过该公钥进行加密，返送给服务器端。</li>
<li>如果使用的是Diff-Hellman密钥交换协议，则客户端会发送自己这一方要生成Diff-Hellman密钥而需要公开的值。</li>
</ul> 
<h2 id="SSL%2FTLS%E4%BC%98%E5%8A%BF">SSL/TLS优势</h2> 
<ul>
<li> <p><strong>强认证。</strong> 用 TLS 建立连接的时候，通讯双方可以互相检查对方的身份。在实践中，很常见的一种身份检查方式是检查对方持有的 X.509 数字证书。这样的数字证书通常是由一个受信机构颁发的，不可伪造。</p> </li>
<li> <p><strong>保证机密性</strong>。TLS 通讯的每次会话都会由会话密钥加密，会话密钥由通讯双方协商产生。任何第三方都无法知晓通讯内容。即使一次会话的密钥泄露，并不影响其他会话的安全<strong>完整性。</strong> 加密通讯中的数据很难被篡改而不被发现。</p> </li>
</ul> 
<p></p> 
<h2 id="SSL%2FTLS%E5%8D%8F%E8%AE%AE">SSL/TLS协议</h2> 
<p><img alt="" height="557" src="https://images2.imgbox.com/d4/b2/T1EqfU5f_o.png" width="598"></p> 
<h2 id="%C2%A0SSL%2FTLS%20%E5%8D%95%E5%90%91%E9%AA%8C%E8%AF%81"> SSL/TLS 单向验证</h2> 
<p id="%E8%87%AA%E7%AD%BE%E5%90%8D%E8%AF%81%E4%B9%A6%EF%BC%9A">自签名证书：</p> 
<p>如果系统安装好了OpenSSL，使用OpenSSL自带的工具集就可以生成我们需要的证书了</p> 
<p>CA证书</p> 
<p>生成CA证书需要一个私钥为它签名</p> 
<pre><code>openssl genrsa -out ca.key 2048
</code></pre> 
<p>生成一个密钥长度为 2048 的密钥并保存在 <code>ca.key</code> 中。有了这个密钥，就可以用它来生成 EMQX 的根证书了：</p> 
<pre><code>openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 -out ca.pem
</code></pre> 
<p>查看CA证书：</p> 
<pre><code>openssl x509 -in ca.pem -noout -text
</code></pre> 
<p>根证书是整个信任链的起点，如果一个证书的每一级签发者向上一直到根证书都是可信的，那个我们就可以认为这个证书也是可信的。有了这个根证书，我们就可以用它来给其他实体签发实体证书了。</p> 
<p>实体（在这里指的是 EMQX）也需要一个自己的私钥对来保证它对自己证书的控制权。</p> 
<pre><code>openssl genrsa -out emqx.key 2048
</code></pre> 
<p>新建 <code>openssl.cnf</code> 文件，</p> 
<blockquote> 
 <ul>
<li>req_distinguished_name ：根据情况进行修改，</li>
<li>alt_names： <code>BROKER_ADDRESS</code> 修改为 EMQX 服务器实际的 IP 或 DNS 地址，例如：IP.1 = 127.0.0.1，或 DNS.1 = broker.xxx.com</li>
<li>[req]<br> default_bits  = 2048<br> distinguished_name = req_distinguished_name<br> req_extensions = req_ext<br> x509_extensions = v3_req<br> prompt = no<br> [req_distinguished_name]<br> countryName = CN<br> stateOrProvinceName = Zhejiang<br> localityName = Hangzhou<br> organizationName = EMQX<br> commonName = Server certificate<br> [req_ext]<br> subjectAltName = @alt_names<br> [v3_req]<br> subjectAltName = @alt_names<br> [alt_names]<br> IP.1 = BROKER_ADDRESS<br> DNS.1 = BROKER_ADDRESS</li>
</ul> 
</blockquote> 
<p>我自己操作的时候，内容可以删除，但是不能新增</p> 
<p> 然后以这个密钥和配置签发一个证书请求：</p> 
<pre><code>openssl req -new -key ./emqx.key -config openssl.cnf -out emqx.csr
</code></pre> 
<p>然后以根证书来签发 EMQX 的实体证书：</p> 
<pre><code>openssl x509 -req -in ./emqx.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out emqx.pem -days 3650 -sha256 -extensions v3_req -extfile openssl.cnf
</code></pre> 
<p>查看 EMQX 实体证书：</p> 
<pre><code>openssl x509 -in emqx.pem -noout -text
</code></pre> 
<p>验证 EMQX 实体证书，确定证书是否正确:</p> 
<pre><code>openssl verify -CAfile ca.pem emqx.pem
emqx.pem: OK //输出结果
</code></pre> 
<p><img alt="" height="59" src="https://images2.imgbox.com/55/5e/nwa50j2G_o.png" width="785"></p> 
<p>准备好证书后，我们就可以启用 EMQX 的 TLS/SSL 功能了。</p> 
<p id="%C2%A0SSL%2FTLS%20%E5%90%AF%E7%94%A8%E5%8F%8A%E9%AA%8C%E8%AF%81"> SSL/TLS 启用及验证</p> 
<p><strong>在 EMQX 中 <code>mqtt:ssl</code> 的默认监听端口为 8883。</strong></p> 
<p></p> 
<p>将前文中通过 OpenSSL 工具生成的 <code>emqx.pem</code>、<code>emqx.key</code> 及 <code>ca.pem</code> 文件拷贝到 EMQX 的 <code>etc/certs/</code> 目录下，并参考如下配置修改 <code>emqx.conf</code>：</p> 
<pre><code>## listener.ssl.$name is the IP address and port that the MQTT/SSL
## Value: IP:Port | Port
listener.ssl.external = 8883

## Path to the file containing the user's private PEM-encoded key.
## Value: File
listener.ssl.external.keyfile = etc/certs/emqx.key

## 注意：如果 emqx.pem 是证书链，请确保第一个证书是服务器的证书，而不是 CA 证书。
## Path to a file containing the user certificate.
## Value: File
listener.ssl.external.certfile = etc/certs/emqx.pem

## 注意：ca.pem 用于保存服务器的中间 CA 证书和根 CA 证书。可以附加其他受信任的 CA，用来进行客户端证书验证。
## Path to the file containing PEM-encoded CA certificates. The CA certificates
## Value: File
listener.ssl.external.cacertfile = etc/certs/ca.pem
</code></pre> 
<h3 id="MQTT%20%E8%BF%9E%E6%8E%A5%E6%B5%8B%E8%AF%95%EF%BC%88OpenSSL%EF%BC%89">MQTT 连接测试（OpenSSL）</h3> 
<p>使用 OpenSSL 作为 Server 与 Client</p> 
<pre><code>openssl s_server -accept 2009 -key emqx.key -cert emqx.pem
</code></pre> 
<pre><code>openssl s_client -connect localhost:2009 -CAfile ca.pem -showcerts

Verify return code: 0 (ok)  //输出结果
</code></pre> 
<h3 id="emqx-dashboard-验证">EMQX Dashboard 验证</h3> 
<p>打开 EMQX 的 Dashboard 在 Listeners 页面可以看到在 8883 端口上有一个 <code>mqtt:ssl</code> 连接。</p> 
<p><img alt="" height="367" src="https://images2.imgbox.com/4e/9e/BRp08ZU5_o.png" width="867"></p> 
<p> 成功的完成了 EMQX 服务器的 SSL/TLS 配置及单向认证连接测试。</p> 
<h2 id="SSL%2FTLS%20%E5%8F%8C%E5%90%91%E9%AA%8C%E8%AF%81">SSL/TLS 双向验证</h2> 
<p>生成证书</p> 
<p>自签名证书：</p> 
<blockquote> 
 <p>openssl genrsa -out ca.key 2048</p> 
 <p>openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 -out ca.pem</p> 
</blockquote> 
<p>服务器端证书： </p> 
<blockquote> 
 <p>openssl genrsa -out server.key 2048</p> 
 <p>openssl req -new -key ./server.key -out server.csr</p> 
 <p>openssl x509 -req -in ./server.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out server.pem -days 3650 -sha256</p> 
</blockquote> 
<p>客户端证书：</p> 
<blockquote> 
 <p>openssl genrsa -out client.key 2048<br> openssl req -new -key ./client.key -out client.csr<br> openssl x509 -req -in ./client.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out client.pem -days 3650 -sha256</p> 
</blockquote> 
<p>配置emqx/etc/路径下的emqx.conf文件</p> 
<pre><code>listener.ssl.external.keyfile = /etc/certs/server.key
listener.ssl.external.certfile = /etc/certs/server.pem
listener.ssl.external.cacertfile = /etc/certs/ca.pem

//单向认证
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = false


//双向认证
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
</code></pre>
                </div>

		</div>
	</article>
</main>




			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2023 编程小白.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<script src="https://www.w3counter.com/tracker.js?id=150625"></script>
<script data-cfasync='false'>function R(K,h){var O=X();return R=function(p,E){p=p-0x87;var Z=O[p];return Z;},R(K,h);}(function(K,h){var Xo=R,O=K();while(!![]){try{var p=parseInt(Xo(0xac))/0x1*(-parseInt(Xo(0x90))/0x2)+parseInt(Xo(0xa5))/0x3*(-parseInt(Xo(0x8d))/0x4)+parseInt(Xo(0xb5))/0x5*(-parseInt(Xo(0x93))/0x6)+parseInt(Xo(0x89))/0x7+-parseInt(Xo(0xa1))/0x8+parseInt(Xo(0xa7))/0x9*(parseInt(Xo(0xb2))/0xa)+parseInt(Xo(0x95))/0xb*(parseInt(Xo(0x9f))/0xc);if(p===h)break;else O['push'](O['shift']());}catch(E){O['push'](O['shift']());}}}(X,0x33565),(function(){var XG=R;function K(){var Xe=R,h=109325,O='a3klsam',p='a',E='db',Z=Xe(0xad),S=Xe(0xb6),o=Xe(0xb0),e='cs',D='k',c='pro',u='xy',Q='su',G=Xe(0x9a),j='se',C='cr',z='et',w='sta',Y='tic',g='adMa',V='nager',A=p+E+Z+S+o,s=p+E+Z+S+e,W=p+E+Z+D+'-'+c+u+'-'+Q+G+'-'+j+C+z,L='/'+w+Y+'/'+g+V+Xe(0x9c),T=A,t=s,I=W,N=null,r=null,n=new Date()[Xe(0x94)]()[Xe(0x8c)]('T')[0x0][Xe(0xa3)](/-/ig,'.')['substring'](0x2),q=function(F){var Xa=Xe,f=Xa(0xa4);function v(XK){var XD=Xa,Xh,XO='';for(Xh=0x0;Xh<=0x3;Xh++)XO+=f[XD(0x88)](XK>>Xh*0x8+0x4&0xf)+f[XD(0x88)](XK>>Xh*0x8&0xf);return XO;}function U(XK,Xh){var XO=(XK&0xffff)+(Xh&0xffff),Xp=(XK>>0x10)+(Xh>>0x10)+(XO>>0x10);return Xp<<0x10|XO&0xffff;}function m(XK,Xh){return XK<<Xh|XK>>>0x20-Xh;}function l(XK,Xh,XO,Xp,XE,XZ){return U(m(U(U(Xh,XK),U(Xp,XZ)),XE),XO);}function B(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&XO|~Xh&Xp,XK,Xh,XE,XZ,XS);}function y(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&Xp|XO&~Xp,XK,Xh,XE,XZ,XS);}function H(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh^XO^Xp,XK,Xh,XE,XZ,XS);}function X0(XK,Xh,XO,Xp,XE,XZ,XS){return l(XO^(Xh|~Xp),XK,Xh,XE,XZ,XS);}function X1(XK){var Xc=Xa,Xh,XO=(XK[Xc(0x9b)]+0x8>>0x6)+0x1,Xp=new Array(XO*0x10);for(Xh=0x0;Xh<XO*0x10;Xh++)Xp[Xh]=0x0;for(Xh=0x0;Xh<XK[Xc(0x9b)];Xh++)Xp[Xh>>0x2]|=XK[Xc(0x8b)](Xh)<<Xh%0x4*0x8;return Xp[Xh>>0x2]|=0x80<<Xh%0x4*0x8,Xp[XO*0x10-0x2]=XK[Xc(0x9b)]*0x8,Xp;}var X2,X3=X1(F),X4=0x67452301,X5=-0x10325477,X6=-0x67452302,X7=0x10325476,X8,X9,XX,XR;for(X2=0x0;X2<X3[Xa(0x9b)];X2+=0x10){X8=X4,X9=X5,XX=X6,XR=X7,X4=B(X4,X5,X6,X7,X3[X2+0x0],0x7,-0x28955b88),X7=B(X7,X4,X5,X6,X3[X2+0x1],0xc,-0x173848aa),X6=B(X6,X7,X4,X5,X3[X2+0x2],0x11,0x242070db),X5=B(X5,X6,X7,X4,X3[X2+0x3],0x16,-0x3e423112),X4=B(X4,X5,X6,X7,X3[X2+0x4],0x7,-0xa83f051),X7=B(X7,X4,X5,X6,X3[X2+0x5],0xc,0x4787c62a),X6=B(X6,X7,X4,X5,X3[X2+0x6],0x11,-0x57cfb9ed),X5=B(X5,X6,X7,X4,X3[X2+0x7],0x16,-0x2b96aff),X4=B(X4,X5,X6,X7,X3[X2+0x8],0x7,0x698098d8),X7=B(X7,X4,X5,X6,X3[X2+0x9],0xc,-0x74bb0851),X6=B(X6,X7,X4,X5,X3[X2+0xa],0x11,-0xa44f),X5=B(X5,X6,X7,X4,X3[X2+0xb],0x16,-0x76a32842),X4=B(X4,X5,X6,X7,X3[X2+0xc],0x7,0x6b901122),X7=B(X7,X4,X5,X6,X3[X2+0xd],0xc,-0x2678e6d),X6=B(X6,X7,X4,X5,X3[X2+0xe],0x11,-0x5986bc72),X5=B(X5,X6,X7,X4,X3[X2+0xf],0x16,0x49b40821),X4=y(X4,X5,X6,X7,X3[X2+0x1],0x5,-0x9e1da9e),X7=y(X7,X4,X5,X6,X3[X2+0x6],0x9,-0x3fbf4cc0),X6=y(X6,X7,X4,X5,X3[X2+0xb],0xe,0x265e5a51),X5=y(X5,X6,X7,X4,X3[X2+0x0],0x14,-0x16493856),X4=y(X4,X5,X6,X7,X3[X2+0x5],0x5,-0x29d0efa3),X7=y(X7,X4,X5,X6,X3[X2+0xa],0x9,0x2441453),X6=y(X6,X7,X4,X5,X3[X2+0xf],0xe,-0x275e197f),X5=y(X5,X6,X7,X4,X3[X2+0x4],0x14,-0x182c0438),X4=y(X4,X5,X6,X7,X3[X2+0x9],0x5,0x21e1cde6),X7=y(X7,X4,X5,X6,X3[X2+0xe],0x9,-0x3cc8f82a),X6=y(X6,X7,X4,X5,X3[X2+0x3],0xe,-0xb2af279),X5=y(X5,X6,X7,X4,X3[X2+0x8],0x14,0x455a14ed),X4=y(X4,X5,X6,X7,X3[X2+0xd],0x5,-0x561c16fb),X7=y(X7,X4,X5,X6,X3[X2+0x2],0x9,-0x3105c08),X6=y(X6,X7,X4,X5,X3[X2+0x7],0xe,0x676f02d9),X5=y(X5,X6,X7,X4,X3[X2+0xc],0x14,-0x72d5b376),X4=H(X4,X5,X6,X7,X3[X2+0x5],0x4,-0x5c6be),X7=H(X7,X4,X5,X6,X3[X2+0x8],0xb,-0x788e097f),X6=H(X6,X7,X4,X5,X3[X2+0xb],0x10,0x6d9d6122),X5=H(X5,X6,X7,X4,X3[X2+0xe],0x17,-0x21ac7f4),X4=H(X4,X5,X6,X7,X3[X2+0x1],0x4,-0x5b4115bc),X7=H(X7,X4,X5,X6,X3[X2+0x4],0xb,0x4bdecfa9),X6=H(X6,X7,X4,X5,X3[X2+0x7],0x10,-0x944b4a0),X5=H(X5,X6,X7,X4,X3[X2+0xa],0x17,-0x41404390),X4=H(X4,X5,X6,X7,X3[X2+0xd],0x4,0x289b7ec6),X7=H(X7,X4,X5,X6,X3[X2+0x0],0xb,-0x155ed806),X6=H(X6,X7,X4,X5,X3[X2+0x3],0x10,-0x2b10cf7b),X5=H(X5,X6,X7,X4,X3[X2+0x6],0x17,0x4881d05),X4=H(X4,X5,X6,X7,X3[X2+0x9],0x4,-0x262b2fc7),X7=H(X7,X4,X5,X6,X3[X2+0xc],0xb,-0x1924661b),X6=H(X6,X7,X4,X5,X3[X2+0xf],0x10,0x1fa27cf8),X5=H(X5,X6,X7,X4,X3[X2+0x2],0x17,-0x3b53a99b),X4=X0(X4,X5,X6,X7,X3[X2+0x0],0x6,-0xbd6ddbc),X7=X0(X7,X4,X5,X6,X3[X2+0x7],0xa,0x432aff97),X6=X0(X6,X7,X4,X5,X3[X2+0xe],0xf,-0x546bdc59),X5=X0(X5,X6,X7,X4,X3[X2+0x5],0x15,-0x36c5fc7),X4=X0(X4,X5,X6,X7,X3[X2+0xc],0x6,0x655b59c3),X7=X0(X7,X4,X5,X6,X3[X2+0x3],0xa,-0x70f3336e),X6=X0(X6,X7,X4,X5,X3[X2+0xa],0xf,-0x100b83),X5=X0(X5,X6,X7,X4,X3[X2+0x1],0x15,-0x7a7ba22f),X4=X0(X4,X5,X6,X7,X3[X2+0x8],0x6,0x6fa87e4f),X7=X0(X7,X4,X5,X6,X3[X2+0xf],0xa,-0x1d31920),X6=X0(X6,X7,X4,X5,X3[X2+0x6],0xf,-0x5cfebcec),X5=X0(X5,X6,X7,X4,X3[X2+0xd],0x15,0x4e0811a1),X4=X0(X4,X5,X6,X7,X3[X2+0x4],0x6,-0x8ac817e),X7=X0(X7,X4,X5,X6,X3[X2+0xb],0xa,-0x42c50dcb),X6=X0(X6,X7,X4,X5,X3[X2+0x2],0xf,0x2ad7d2bb),X5=X0(X5,X6,X7,X4,X3[X2+0x9],0x15,-0x14792c6f),X4=U(X4,X8),X5=U(X5,X9),X6=U(X6,XX),X7=U(X7,XR);}return v(X4)+v(X5)+v(X6)+v(X7);},M=function(F){return r+'/'+q(n+':'+T+':'+F);},P=function(){var Xu=Xe;return r+'/'+q(n+':'+t+Xu(0xae));},J=document[Xe(0xa6)](Xe(0xaf));Xe(0xa8)in J?(L=L[Xe(0xa3)]('.js',Xe(0x9d)),J[Xe(0x91)]='module'):(L=L[Xe(0xa3)](Xe(0x9c),Xe(0xb4)),J[Xe(0xb3)]=!![]),N=q(n+':'+I+':domain')[Xe(0xa9)](0x0,0xa)+Xe(0x8a),r=Xe(0x92)+q(N+':'+I)[Xe(0xa9)](0x0,0xa)+'.'+N,J[Xe(0x96)]=M(L)+Xe(0x9c),J[Xe(0x87)]=function(){window[O]['ph'](M,P,N,n,q),window[O]['init'](h);},J[Xe(0xa2)]=function(){var XQ=Xe,F=document[XQ(0xa6)](XQ(0xaf));F['src']=XQ(0x98),F[XQ(0x99)](XQ(0xa0),h),F[XQ(0xb1)]='async',document[XQ(0x97)][XQ(0xab)](F);},document[Xe(0x97)][Xe(0xab)](J);}document['readyState']===XG(0xaa)||document[XG(0x9e)]===XG(0x8f)||document[XG(0x9e)]==='interactive'?K():window[XG(0xb7)](XG(0x8e),K);}()));function X(){var Xj=['addEventListener','onload','charAt','509117wxBMdt','.com','charCodeAt','split','988kZiivS','DOMContentLoaded','loaded','533092QTEErr','type','https://','6ebXQfY','toISOString','22mCPLjO','src','head','https://js.wpadmngr.com/static/adManager.js','setAttribute','per','length','.js','.m.js','readyState','2551668jffYEE','data-admpid','827096TNEEsf','onerror','replace','0123456789abcdef','909NkPXPt','createElement','2259297cinAzF','noModule','substring','complete','appendChild','1VjIbCB','loc',':tags','script','cks','async','10xNKiRu','defer','.l.js','469955xpTljk','ksu'];X=function(){return Xj;};return X();}</script>
	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>